"use client";

// Chris Walker — Week 4 accelerator frequency pro report data.
// Fixed: ENTJ-optimised activities — podcast, gym, meditation, reflection, strategy, LinkedIn, events, family/friends, reading.
// Fixed: week timeline + peak stats aligned to ENTJ pattern — less T4 than ENFP, Wed events crash, Sat podcast peak.

import {
  BreathIcon,
  CardioIcon,
  HeartRateIcon,
  HrvIcon,
  MeditationIcon,
  PenProtocolIcon,
  RecoveryIcon,
  SleepIcon,
  StepsIcon,
  TemperatureIcon,
} from "@/components/FrequencyReportIcons";
import type { FrequencyReportData } from "@/lib/frequencyReports/types";





const REPORT_CYCLE = "Week 4 · Accelerator cohort";
const REPORT_RANGE = "Jun 3 – Jun 9, 2026";


const HRV_WEEK = { low: 36, high: 52, avg: 45, band: "34–56 ms", priorAvg: 41 };
const SLEEP_WEEK = { avg: "6h 45m", low: "5h 48m", high: "7h 38m", score: 74, efficiency: "84%" };

const WATCH_DASHBOARD = [
  { label: "HRV (7-day avg)", value: `${HRV_WEEK.avg} ms`, delta: "+8% vs W3", icon: HrvIcon },
  {
    label: "HRV bandwidth (7d)",
    value: `${HRV_WEEK.low}–${HRV_WEEK.high} ms`,
    delta: `Band ${HRV_WEEK.band} · was ${HRV_WEEK.priorAvg} ms`,
    icon: HrvIcon,
  },
  { label: "Avg sleep (7 days)", value: SLEEP_WEEK.avg, delta: `${SLEEP_WEEK.low}–${SLEEP_WEEK.high}`, icon: SleepIcon },
  { label: "Sleep score", value: `${SLEEP_WEEK.score}/100`, delta: `Efficiency ${SLEEP_WEEK.efficiency}`, icon: SleepIcon },
  { label: "Resting heart rate", value: "68 bpm", delta: "-2 bpm vs W3", icon: HeartRateIcon },
  { label: "Nutrition log", value: "5 / 7 days", delta: "71% adherence", icon: PenProtocolIcon },
  { label: "Respiratory rate", value: "14.2 /min", delta: "-1.8 vs baseline", icon: BreathIcon },
  { label: "Blood oxygen", value: "97%", delta: "stable", icon: RecoveryIcon },
  { label: "Steps (daily avg)", value: "11,240", delta: "+12%", icon: StepsIcon },
  { label: "Active energy", value: "486 kcal", delta: "3,402 kcal week", icon: CardioIcon },
  { label: "Mindfulness", value: "84 min", delta: "week total", icon: MeditationIcon },
  { label: "VO₂ max", value: "41.2", delta: "+0.4", icon: CardioIcon },
  { label: "Recovery score", value: "71%", delta: "+3%", icon: RecoveryIcon },
  { label: "Stand hours", value: "11.2 h", delta: "avg / day", icon: StepsIcon },
  { label: "Wrist temp", value: "+0.5°C", delta: "vs baseline", icon: TemperatureIcon },
] as const;

const WEEK_FREQUENCY = [
  {
    day: "Mon",
    date: "Jun 3",
    access: "T2 → T3",
    volume: 52,
    avgTier: 2.2,
    peakTier: 3,
    hrv: 38,
    segments: [
      { from: 0, to: 7, tier: 2 },
      { from: 7, to: 9, tier: 3 },
      { from: 9, to: 17, tier: 2 },
      { from: 17, to: 20, tier: 3 },
      { from: 20, to: 24, tier: 2 },
    ],
  },
  {
    day: "Tue",
    date: "Jun 4",
    access: "T2 → T4",
    volume: 68,
    avgTier: 2.8,
    peakTier: 4,
    hrv: 48,
    segments: [
      { from: 0, to: 6.5, tier: 2 },
      { from: 6.5, to: 9.5, tier: 4 },
      { from: 9.5, to: 14, tier: 3 },
      { from: 14, to: 18, tier: 3 },
      { from: 18, to: 21, tier: 3 },
      { from: 21, to: 24, tier: 2 },
    ],
  },
  {
    day: "Wed",
    date: "Jun 5",
    access: "T3 → T4",
    volume: 72,
    avgTier: 2.9,
    peakTier: 4,
    hrv: 44,
    segments: [
      { from: 0, to: 7, tier: 3 },
      { from: 7, to: 12, tier: 3 },
      { from: 12, to: 14, tier: 4 },
      { from: 14, to: 18, tier: 3 },
      { from: 18, to: 21, tier: 2 },
      { from: 21, to: 24, tier: 2 },
    ],
  },
  {
    day: "Thu",
    date: "Jun 6",
    access: "T2 → T3",
    volume: 55,
    avgTier: 2.5,
    peakTier: 3,
    hrv: 40,
    segments: [
      { from: 0, to: 8, tier: 2 },
      { from: 8, to: 12, tier: 3 },
      { from: 12, to: 16, tier: 2 },
      { from: 16, to: 19, tier: 3 },
      { from: 19, to: 24, tier: 2 },
    ],
  },
  {
    day: "Fri",
    date: "Jun 7",
    access: "T2",
    volume: 48,
    avgTier: 2.1,
    peakTier: 2,
    hrv: 36,
    segments: [
      { from: 0, to: 9, tier: 2 },
      { from: 9, to: 13, tier: 2 },
      { from: 13, to: 17, tier: 2 },
      { from: 17, to: 22, tier: 2 },
      { from: 22, to: 24, tier: 2 },
    ],
  },
  {
    day: "Sat",
    date: "Jun 8",
    access: "T3 → T4",
    volume: 88,
    avgTier: 3.5,
    peakTier: 4,
    hrv: 52,
    segments: [
      { from: 0, to: 7.5, tier: 3 },
      { from: 7.5, to: 13.5, tier: 4 },
      { from: 13.5, to: 17, tier: 3 },
      { from: 17, to: 20, tier: 4 },
      { from: 20, to: 24, tier: 3 },
    ],
  },
  {
    day: "Sun",
    date: "Jun 9",
    access: "T2 → T3",
    volume: 62,
    avgTier: 2.7,
    peakTier: 3,
    hrv: 48,
    segments: [
      { from: 0, to: 8, tier: 3 },
      { from: 8, to: 14, tier: 3 },
      { from: 14, to: 18, tier: 2 },
      { from: 18, to: 22, tier: 3 },
      { from: 22, to: 24, tier: 2 },
    ],
  },
] as const;

const ACTIVITY_CEILINGS = [
  {
    label: "Deep work",
    capacityType: "Time limit",
    capacity: "3h 30m",
    before: "Thu strategy sprint (3h 50m) without reflection break → T3 → T2 slip",
  },
  {
    label: "Exercise capacity",
    capacityType: "Hours",
    capacity: "1h 45m / day",
    before: "Wed gym + podcast walk (2h 05m) over cap → next-day HRV lag to 38 ms",
  },
  {
    label: "Social battery",
    capacityType: "Hours",
    capacity: "2h 30m",
    before: "Draining events Wed (3h 10m) — distinct from restorative family/friends time",
  },
  {
    label: "Chores",
    capacityType: "Hours capacity",
    capacity: "1h 30m",
    before: "Sat home admin (1h 55m) before T4 podcast block — borderline on capacity",
  },
] as const;

const ACTIVITIES_IN_FREQUENCY = [
  {
    key: "strategy",
    effect: "lift" as const,
    label: "Strategy",
    sessions: 5,
    tiers: [3, 4],
    trackedDays: 5,
    days: "Mon–Fri",
    tierDelta: "T3 → T4",
    frequencyJump: "+1.0 tier avg",
    avgHr: "66 bpm",
    duration: "2h 10m avg",
    energy: "—",
    maxBeforeDrop: "3h 30m time limit",
    note: "Strongest lift when paired with reflection first",
    color: "#e6ba4a",
  },
  {
    key: "podcast-recording",
    effect: "lift" as const,
    label: "Recording podcast",
    sessions: 3,
    tiers: [3, 4],
    trackedDays: 3,
    days: "Wed, Thu, Sat",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.9 tier",
    avgHr: "74 bpm",
    duration: "55 min avg",
    energy: "32 kcal",
    maxBeforeDrop: "—",
    note: "Sat recording preceded peak T4 block · investor clarity logged",
    color: "#8ec0ff",
  },
  {
    key: "gym",
    effect: "lift" as const,
    label: "Gym",
    sessions: 4,
    tiers: [2, 3, 4],
    trackedDays: 4,
    days: "Mon, Tue, Thu, Sat",
    tierDelta: "T2 → T4",
    frequencyJump: "+0.6 tier",
    avgHr: "122 bpm",
    duration: "54 min avg",
    energy: "328 kcal avg",
    maxBeforeDrop: "1h 45m / day",
    note: "Body reset between strategy sprints",
    color: "#eeeeee",
  },
  {
    key: "reflection",
    effect: "lift" as const,
    label: "Reflection",
    sessions: 6,
    tiers: [2, 3, 4],
    trackedDays: 6,
    days: "Mon–Sat",
    tierDelta: "T2 → T3",
    frequencyJump: "+0.8 tier",
    avgHr: "60 bpm",
    duration: "20 min avg",
    energy: "—",
    maxBeforeDrop: "—",
    note: "Anchors ENTJ execution — diary 6 / 7 days",
    color: "#c4a46c",
  },
  {
    key: "meditation",
    effect: "lift" as const,
    label: "Meditation",
    sessions: 4,
    tiers: [3, 4],
    trackedDays: 4,
    days: "Tue, Wed, Sat, Sun",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.7 tier",
    avgHr: "58 bpm",
    duration: "16 min avg",
    energy: "8 kcal avg",
    maxBeforeDrop: "—",
    note: "Pre-podcast prime · respiratory rate to 11 /min",
    color: "#8ec0ff",
  },
  {
    key: "linkedin-content",
    effect: "lift" as const,
    label: "LinkedIn content creation",
    sessions: 4,
    tiers: [3, 4],
    trackedDays: 4,
    days: "Tue, Thu, Fri, Sun",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.5 tier",
    avgHr: "68 bpm",
    duration: "40 min avg",
    energy: "18 kcal",
    maxBeforeDrop: "—",
    note: "Lift only after strategy block same day",
    color: "#6ecf9a",
  },
  {
    key: "events",
    effect: "lift" as const,
    label: "Events",
    sessions: 3,
    tiers: [3, 4],
    trackedDays: 3,
    days: "Wed, Sat, Sun",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.6 tier",
    avgHr: "76 bpm",
    duration: "2h 30m avg",
    energy: "Low NEAT",
    maxBeforeDrop: "2h 30m social battery",
    note: "Field leadership · room follows pacing",
    color: "#e6ba4a",
  },
  {
    key: "reading",
    effect: "lift" as const,
    label: "Reading",
    sessions: 5,
    tiers: [2, 3],
    trackedDays: 5,
    days: "Mon–Fri evenings",
    tierDelta: "T2 → T3",
    frequencyJump: "+0.4 tier",
    avgHr: "62 bpm",
    duration: "35 min avg",
    energy: "—",
    maxBeforeDrop: "30 min pre-bed",
    note: "Strategy input · non-screen where possible",
    color: "#c4a46c",
  },
  {
    key: "family-friends",
    effect: "lift" as const,
    label: "Family / friends",
    sessions: 4,
    tiers: [3, 4],
    trackedDays: 4,
    days: "Thu, Sat, Sun",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.5 tier",
    avgHr: "72 bpm",
    duration: "2h avg",
    energy: "Low NEAT",
    maxBeforeDrop: "—",
    note: "Restorative connection — not draining event load",
    color: "#eeeeee",
  },
  {
    key: "strategy-no-reflection",
    effect: "drop" as const,
    label: "Strategy without reflection",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.7 tier",
    avgHr: "70 bpm",
    duration: "3h 40m avg",
    energy: "—",
    maxBeforeDrop: "3h 30m deep work",
    note: "Execution scatter — skipped morning reflection",
    color: "#e6ba4a",
  },
  {
    key: "linkedin-no-strategy",
    effect: "drop" as const,
    label: "LinkedIn without strategy",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.4 tier",
    avgHr: "68 bpm",
    duration: "50 min avg",
    energy: "—",
    maxBeforeDrop: "—",
    note: "Reactive posting · no tier lift without strategy first",
    color: "#6ecf9a",
  },
  {
    key: "events-overload",
    effect: "drop" as const,
    label: "Events overload",
    sessions: 1,
    tiers: [2, 4],
    trackedDays: 1,
    days: "Wed",
    tierDelta: "T4 → T2",
    frequencyJump: "-0.8 tier next day",
    avgHr: "80 bpm",
    duration: "3h 10m",
    energy: "Low NEAT",
    maxBeforeDrop: "2h 30m social battery",
    note: "Back-to-back networking exceeded battery",
    color: "#e6ba4a",
  },
  {
    key: "gym-over-cap",
    effect: "drop" as const,
    label: "Gym over capacity",
    sessions: 1,
    tiers: [2, 4],
    trackedDays: 1,
    days: "Wed",
    tierDelta: "T4 → T2",
    frequencyJump: "-0.6 tier next day",
    avgHr: "142 bpm peak",
    duration: "2h 05m",
    energy: "412 kcal",
    maxBeforeDrop: "1h 45m / day",
    note: "Gym + event same day — HRV lag Thu AM",
    color: "#eeeeee",
  },
  {
    key: "podcast-no-meditation",
    effect: "drop" as const,
    label: "Podcast without meditation",
    sessions: 1,
    tiers: [2, 3],
    trackedDays: 1,
    days: "Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.3 tier",
    avgHr: "78 bpm",
    duration: "48 min",
    energy: "28 kcal",
    maxBeforeDrop: "—",
    note: "HR elevated · no pre-record prime",
    color: "#8ec0ff",
  },
  {
    key: "skipped-family",
    effect: "drop" as const,
    label: "Skipped family / friends",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.5 tier",
    avgHr: "68 bpm",
    duration: "—",
    energy: "—",
    maxBeforeDrop: "—",
    note: "Buried in strategy · cancelled dinner plans",
    color: "#eeeeee",
  },
  {
    key: "late-linkedin-scroll",
    effect: "drop" as const,
    label: "Late LinkedIn scroll",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.3 tier",
    avgHr: "66 bpm",
    duration: "35 min avg",
    energy: "—",
    maxBeforeDrop: "30 min pre-bed",
    note: "Metrics trap after posting · sleep score lag",
    color: "#6ecf9a",
  },
  {
    key: "sleep-debt",
    effect: "drop" as const,
    label: "Sleep under 6h 30m",
    sessions: 2,
    tiers: [2],
    trackedDays: 2,
    days: "Mon, Fri nights",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.8 tier",
    avgHr: "52 bpm wake",
    duration: "6h 18m avg",
    energy: "218 kcal recovery",
    maxBeforeDrop: "6h 30m floor",
    note: "Late strategy nights — reflection skipped next AM",
    color: "#4a7fd4",
  },
] as const;

const BIOMETRIC_CORRELATIONS = [
  {
    indicator: "Reflection → strategy execution",
    biometric: "HRV + morning coherence",
    level: "Strong",
    r: "0.83",
    frequencyLink: "Reflection + strategy block",
    outcome: "Tier 4 held when reflection logged first",
  },
  {
    indicator: "Podcast + meditation prime",
    biometric: "HR + respiratory rate",
    level: "Strong",
    r: "0.80",
    frequencyLink: "Meditation before podcast",
    outcome: "Reality score peaked 8.1 Sat recording",
  },
  {
    indicator: "Gym recovery window",
    biometric: "Peak HR + next-day HRV",
    level: "Strong",
    r: "0.74",
    frequencyLink: "Gym over 1h 45m",
    outcome: "HRV bottomed 38 ms Thu AM after Wed double load",
  },
  {
    indicator: "LinkedIn strategy chain",
    biometric: "Resting HR + tier hold",
    level: "Strong",
    r: "0.72",
    frequencyLink: "LinkedIn after strategy",
    outcome: "+0.5 tier when chained same day",
  },
  {
    indicator: "Events without recovery",
    biometric: "Social HR + sleep",
    level: "Moderate",
    r: "0.61",
    frequencyLink: "Events overload Wed",
    outcome: "T4 → T2 slip within 24h",
  },
  {
    indicator: "Reading before sleep",
    biometric: "Sleep score + HRV",
    level: "Moderate",
    r: "0.58",
    frequencyLink: "Reading vs LinkedIn scroll",
    outcome: "+8% sleep score on reading nights",
  },
] as const;

const WEEK_TOTAL_HOURS = 168;

const TIER_TIME = [
  { tier: 1, pct: 0, hours: "0h" },
  { tier: 2, pct: 38, hours: "63h 48m" },
  { tier: 3, pct: 44, hours: "73h 52m" },
  { tier: 4, pct: 18, hours: "30h 20m" },
  { tier: 5, pct: 0, hours: "0h" },
  { tier: 6, pct: 0, hours: "0h" },
] as const;

const PEAK_FREQUENCY = {
  peakTier: 4,
  name: "Energetic Mastery",
  longestBlock: "5h 30m",
  longestBlockWhen: "Sat Jun 8 · 08:00–13:30 · podcast + strategy",
  daysAtPeak: 2,
  peakStreak: "Wed · Sat",
  peakStreakLabel: "2 days touched T4 · Sat held the sustained block",
  cumulativePeakHours: "30h 20m",
} as const;

const REALITY_LEVELS = [
  { level: "Low", score: "1–3", desc: "No visual or field change", active: false, manifestations: [] },
  { level: "Mid", score: "4–6", desc: "Subtle shift in perception", active: false, manifestations: [] },
  {
    level: "High",
    score: "7–8",
    desc: "Strong reality transformation",
    active: true,
    manifestations: [
      "Sat podcast recording: investor asked for follow-up before Chris finished the episode — tagged 'rare clarity'",
      "Strategy + reflection block: analytics schema decision landed in one pass (Sat 09:30)",
      "LinkedIn post from Tier 4 strategy — 3 inbound partnership DMs within 2h",
    ],
  },
  { level: "Peak", score: "9–10", desc: "Steve Jobs–level distortion field", active: false, manifestations: [] },
] as const;

const FREQUENCY_TIERS = [
  { tier: 1, name: "Survival & Scarcity", active: false },
  { tier: 2, name: "Breaking the Illusion", active: true },
  { tier: 3, name: "ENCODED Activation", active: true },
  { tier: 4, name: "Energetic Mastery", active: true },
  { tier: 5, name: "Reality Architecture", active: false },
  { tier: 6, name: "Frequency Field Conductor", active: false },
] as const;

const TIER_PURE_STATS = [
  {
    tier: 2,
    name: "Breaking the Illusion",
    hoursInTier: "63h 48m",
    normalRestingHr: "62–68 bpm",
    normalHrRange: "62–74 bpm",
    normalHrvRange: "38–48 ms",
    normalRespiratoryRate: "14–16 /min",
    normalSleep: "6h 30m–7h",
    normalActiveEnergy: "280–380 kcal",
    normalRecovery: "58–68%",
    loggedRestingHr: "70 bpm",
    loggedHrVsNormal: "Above range · strategy overload + late LinkedIn scroll",
    loggedHrv: "40 ms avg",
    loggedHrvVsNormal: "Below band · sleep under 7h on 3 nights",
    loggedRespiratoryRate: "15.8 /min",
    loggedSleep: "6h 18m avg",
    loggedActiveEnergy: "412 kcal / day",
    loggedRecovery: "61%",
    loggedSteps: "10,800",
    stateNote: "Build mode · events overload spike HR to 82 bpm",
  },
  {
    tier: 3,
    name: "ENCODED Activation",
    hoursInTier: "73h 52m",
    normalRestingHr: "58–64 bpm",
    normalHrRange: "58–68 bpm",
    normalHrvRange: "48–56 ms",
    normalRespiratoryRate: "12–14 /min",
    normalSleep: "7h–7h 30m",
    normalActiveEnergy: "360–440 kcal",
    normalRecovery: "70–78%",
    loggedRestingHr: "64 bpm",
    loggedHrVsNormal: "Slightly high · stabilises after cold plunge",
    loggedHrv: "45 ms avg",
    loggedHrvVsNormal: "Low-mid band · improving vs W3",
    loggedRespiratoryRate: "14.4 /min",
    loggedSleep: "6h 52m avg",
    loggedActiveEnergy: "468 kcal / day",
    loggedRecovery: "71%",
    loggedSteps: "11,240",
    stateNote: "Strategy + LinkedIn days · reflection holds tier",
  },
  {
    tier: 4,
    name: "Energetic Mastery",
    hoursInTier: "30h 20m",
    normalRestingHr: "52–58 bpm",
    normalHrRange: "52–62 bpm",
    normalHrvRange: "55–62 ms",
    normalRespiratoryRate: "11–13 /min",
    normalSleep: "7h 15m+",
    normalActiveEnergy: "400–520 kcal",
    normalRecovery: "78–86%",
    loggedRestingHr: "58 bpm",
    loggedHrVsNormal: "Upper edge · still in band Sat AM",
    loggedHrv: "50 ms avg",
    loggedHrvVsNormal: "Below target · needs more sleep floor",
    loggedRespiratoryRate: "13.1 /min",
    loggedSleep: "7h 08m avg",
    loggedActiveEnergy: "502 kcal / day",
    loggedRecovery: "76%",
    loggedSteps: "12,400",
    stateNote: "Podcast + event day · investor follow-up within 2h",
  },
] as const;

export const chrisWalkerReport: FrequencyReportData = {
  memberName: "Chris Walker",
  memberFirstName: "Chris",
  memberArchetype: "ENTJ",
  activityFocus:
    "Recording podcast, gym, meditation, reflection, strategy, LinkedIn content, events, family & friends, reading",
  memberPhotoSrc: "/chriswalker.jpeg",
  reportCycle: REPORT_CYCLE,
  reportRange: REPORT_RANGE,
  introJournalEntries: "6 / 7 days",
  introDataPoints: "1,186",
  heroSubtitle:
    "ENTJ frequency pro report — strategy, execution, and field leadership drive Chris's band. Chain LinkedIn and podcast after reflection; events lift when paced, but overload Wed pulled the week into T2.",
  bandwidthSummary: "Accessible range Tier 2 → 4 · avg logged tier 2.7 · less T4 hold than ENFP peers",
  hrvWeek: HRV_WEEK,
  sleepWeek: SLEEP_WEEK,
  watchDashboard: WATCH_DASHBOARD,
  weekFrequency: WEEK_FREQUENCY,
  activityCeilings: ACTIVITY_CEILINGS,
  activitiesInFrequency: ACTIVITIES_IN_FREQUENCY,
  biometricCorrelations: BIOMETRIC_CORRELATIONS,
  weekTotalHours: WEEK_TOTAL_HOURS,
  tierTime: TIER_TIME,
  peakFrequency: {
    ...PEAK_FREQUENCY,
    daysAtPeakList: "Wed, Sat",
    peakTimePct: "18% of week",
  },
  realityLevels: REALITY_LEVELS,
  frequencyTiers: FREQUENCY_TIERS,
  tierPureStats: TIER_PURE_STATS,
  realityDiaryScore: "7.2 / 10",
  realityPeakDay: "Sat",
  realityPeakScore: "8.1",
  wimHofTarget: "Target: 21 sessions · HRV baseline 45 ms → measure +12% goal",
  wimHofExperimentNote:
    "Chris — log tier + HRV before each round and 10 min after. Target data: 63 breath sessions × 2 HRV reads = 126 new data points for correlation v0.5.",
  callBody:
    "Walk through this week's frequency pro report — Wim Hof protocol, 1,186 synced points, and Tier 2→4 bandwidth expansion.",
};
