"use client";

// Courtney Confare — Week 4 accelerator frequency pro report data.
// Fixed: ENFP-optimised activities — Instagram, design management, course building, exercise, reflection, friends/family.
// Fixed: ENFP narrative — creative lifts/drops, reflection anchors scatter, comparison + isolation traps.
// Fixed: removed heroSubtitle copy per request — ENFP creative/Instagram summary no longer shown under report header.
// Fixed: removed sleep stages + HRV activity insights from report UI — data kept optional on type only.

import {
  BreathIcon,
  CardioIcon,
  HeartRateIcon,
  HrvIcon,
  MeditationIcon,
  PenProtocolIcon,
  RecoveryIcon,
  SleepIcon,
  StepsIcon,
  TemperatureIcon,
} from "@/components/FrequencyReportIcons";
import type { FrequencyReportData } from "@/lib/frequencyReports/types";





const REPORT_CYCLE = "Week 4 · Accelerator cohort";
const REPORT_RANGE = "Jun 3 – Jun 9, 2026";


const HRV_WEEK = { low: 42, high: 58, avg: 51, band: "38–62 ms", priorAvg: 47 };
const SLEEP_WEEK = { avg: "7h 12m", low: "6h 12m", high: "8h 02m", score: 82, efficiency: "89%" };

const WATCH_DASHBOARD = [
  { label: "HRV (7-day avg)", value: `${HRV_WEEK.avg} ms`, delta: "+8% vs W3", icon: HrvIcon },
  {
    label: "HRV bandwidth (7d)",
    value: `${HRV_WEEK.low}–${HRV_WEEK.high} ms`,
    delta: `Band ${HRV_WEEK.band} · was ${HRV_WEEK.priorAvg} ms`,
    icon: HrvIcon,
  },
  { label: "Avg sleep (7 days)", value: SLEEP_WEEK.avg, delta: `${SLEEP_WEEK.low}–${SLEEP_WEEK.high}`, icon: SleepIcon },
  { label: "Sleep score", value: `${SLEEP_WEEK.score}/100`, delta: `Efficiency ${SLEEP_WEEK.efficiency}`, icon: SleepIcon },
  { label: "Resting heart rate", value: "64 bpm", delta: "-3 bpm vs W3", icon: HeartRateIcon },
  { label: "Nutrition log", value: "6 / 7 days", delta: "86% adherence", icon: PenProtocolIcon },
  { label: "Respiratory rate", value: "14.2 /min", delta: "-1.8 vs baseline", icon: BreathIcon },
  { label: "Blood oxygen", value: "97%", delta: "stable", icon: RecoveryIcon },
  { label: "Steps (daily avg)", value: "8,420", delta: "+6%", icon: StepsIcon },
  { label: "Active energy", value: "412 kcal", delta: "2,884 kcal week", icon: CardioIcon },
  { label: "Mindfulness", value: "126 min", delta: "week total", icon: MeditationIcon },
  { label: "VO₂ max", value: "38.4", delta: "+0.6", icon: CardioIcon },
  { label: "Recovery score", value: "78%", delta: "+6%", icon: RecoveryIcon },
  { label: "Stand hours", value: "11.2 h", delta: "avg / day", icon: StepsIcon },
  { label: "Wrist temp", value: "+0.3°C", delta: "vs baseline", icon: TemperatureIcon },
] as const;

const WEEK_FREQUENCY = [
  {
    day: "Mon",
    date: "Jun 3",
    access: "T2 → T3",
    volume: 64,
    avgTier: 2.4,
    peakTier: 3,
    hrv: 44,
    segments: [
      { from: 0, to: 6.5, tier: 2 },
      { from: 6.5, to: 9, tier: 3 },
      { from: 9, to: 13, tier: 2 },
      { from: 13, to: 17, tier: 3 },
      { from: 17, to: 22, tier: 2 },
      { from: 22, to: 24, tier: 2 },
    ],
  },
  {
    day: "Tue",
    date: "Jun 4",
    access: "T2 → T4",
    volume: 78,
    avgTier: 3.1,
    peakTier: 4,
    hrv: 52,
    segments: [
      { from: 0, to: 7, tier: 2 },
      { from: 7, to: 10, tier: 4 },
      { from: 10, to: 14, tier: 3 },
      { from: 14, to: 18, tier: 3 },
      { from: 18, to: 21, tier: 4 },
      { from: 21, to: 24, tier: 3 },
    ],
  },
  {
    day: "Wed",
    date: "Jun 5",
    access: "T3 → T4",
    volume: 81,
    avgTier: 3.2,
    peakTier: 4,
    hrv: 53,
    segments: [
      { from: 0, to: 7.5, tier: 3 },
      { from: 7.5, to: 12, tier: 3 },
      { from: 12, to: 15, tier: 4 },
      { from: 15, to: 19, tier: 3 },
      { from: 19, to: 23, tier: 4 },
      { from: 23, to: 24, tier: 3 },
    ],
  },
  {
    day: "Thu",
    date: "Jun 6",
    access: "T3 → T4",
    volume: 92,
    avgTier: 3.6,
    peakTier: 4,
    hrv: 58,
    segments: [
      { from: 0, to: 7, tier: 3 },
      { from: 7, to: 11, tier: 4 },
      { from: 11, to: 14, tier: 4 },
      { from: 14, to: 17, tier: 3 },
      { from: 17, to: 21, tier: 4 },
      { from: 21, to: 24, tier: 3 },
    ],
  },
  {
    day: "Fri",
    date: "Jun 7",
    access: "T2 → T3",
    volume: 58,
    avgTier: 2.3,
    peakTier: 3,
    hrv: 42,
    segments: [
      { from: 0, to: 5.5, tier: 2 },
      { from: 5.5, to: 9, tier: 2 },
      { from: 9, to: 13, tier: 3 },
      { from: 13, to: 18, tier: 2 },
      { from: 18, to: 22, tier: 2 },
      { from: 22, to: 24, tier: 2 },
    ],
  },
  {
    day: "Sat",
    date: "Jun 8",
    access: "T3 → T4",
    volume: 88,
    avgTier: 3.5,
    peakTier: 4,
    hrv: 57,
    segments: [
      { from: 0, to: 8, tier: 3 },
      { from: 8, to: 12, tier: 4 },
      { from: 12, to: 16, tier: 3 },
      { from: 16, to: 20, tier: 4 },
      { from: 20, to: 24, tier: 3 },
    ],
  },
  {
    day: "Sun",
    date: "Jun 9",
    access: "T2 → T4",
    volume: 74,
    avgTier: 3.0,
    peakTier: 4,
    hrv: 54,
    segments: [
      { from: 0, to: 7.5, tier: 3 },
      { from: 7.5, to: 11, tier: 3 },
      { from: 11, to: 15, tier: 4 },
      { from: 15, to: 19, tier: 3 },
      { from: 19, to: 24, tier: 2 },
    ],
  },
] as const;

const ACTIVITY_CEILINGS = [
  {
    label: "Deep work",
    capacityType: "Time limit",
    capacity: "4h",
    before: "Mon course-building sprint (4h 20m) without reflection break → T3 → T2 slip",
  },
  {
    label: "Exercise capacity",
    capacityType: "Hours",
    capacity: "1h 20m / day",
    before: "Thu gym + run (80 min) over cap → Fri dropped to T2",
  },
  {
    label: "Social battery",
    capacityType: "Hours",
    capacity: "3h",
    before: "Draining meetings Mon + Fri (4h each) — distinct from restorative friends/family time",
  },
  {
    label: "Chores",
    capacityType: "Hours capacity",
    capacity: "2h",
    before: "Fri home reset + errands (2h 25m) ate window before friends dinner",
  },
] as const;

const ACTIVITIES_IN_FREQUENCY = [
  {
    key: "instagram-content",
    effect: "lift" as const,
    label: "Instagram content",
    sessions: 6,
    tiers: [3, 4],
    trackedDays: 6,
    days: "Mon–Sat",
    tierDelta: "T3 → T4",
    frequencyJump: "+1.1 tier avg",
    avgHr: "72 bpm",
    duration: "45 min avg",
    energy: "28 kcal",
    maxBeforeDrop: "—",
    note: "ENFP creative flow — strongest lift when batching after reflection",
    color: "#e6ba4a",
  },
  {
    key: "design-management",
    effect: "lift" as const,
    label: "Design management",
    sessions: 5,
    tiers: [3, 4],
    trackedDays: 5,
    days: "Tue–Sat",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.9 tier",
    avgHr: "68 bpm",
    duration: "1h 50m avg",
    energy: "42 kcal",
    maxBeforeDrop: "3h stakeholder block",
    note: "Visual leadership + people energy — holds T4 when paced",
    color: "#8ec0ff",
  },
  {
    key: "course-building",
    effect: "lift" as const,
    label: "Course building",
    sessions: 4,
    tiers: [3, 4],
    trackedDays: 4,
    days: "Mon, Wed, Thu, Sat",
    tierDelta: "T3 → T4",
    frequencyJump: "+1.0 tier",
    avgHr: "66 bpm",
    duration: "2h 20m avg",
    energy: "—",
    maxBeforeDrop: "4h time limit",
    note: "Peak ENFP builder mode — Thu block hit reality score 8.4",
    color: "#c4a46c",
  },
  {
    key: "exercise",
    effect: "lift" as const,
    label: "Exercise",
    sessions: 4,
    tiers: [2, 3, 4],
    trackedDays: 4,
    days: "Mon, Tue, Thu, Sat",
    tierDelta: "T2 → T4",
    frequencyJump: "+0.6 tier",
    avgHr: "118 bpm",
    duration: "48 min avg",
    energy: "298 kcal avg",
    maxBeforeDrop: "1h 20m / day",
    note: "Gym + walks — body reset between creative sprints",
    color: "#6ecf9a",
  },
  {
    key: "reflection",
    effect: "lift" as const,
    label: "Reflection",
    sessions: 7,
    tiers: [2, 3, 4],
    trackedDays: 7,
    days: "Daily",
    tierDelta: "T2 → T3",
    frequencyJump: "+0.8 tier",
    avgHr: "60 bpm",
    duration: "22 min avg",
    energy: "—",
    maxBeforeDrop: "—",
    note: "Morning pages + ENCODED journal — anchors scattered ideation",
    color: "#c4a46c",
  },
  {
    key: "friends-family",
    effect: "lift" as const,
    label: "Friends / family",
    sessions: 5,
    tiers: [3, 4],
    trackedDays: 5,
    days: "Wed, Thu, Sat, Sun",
    tierDelta: "T3 → T4",
    frequencyJump: "+0.7 tier",
    avgHr: "74 bpm",
    duration: "2h 10m avg",
    energy: "Low NEAT",
    maxBeforeDrop: "—",
    note: "Restorative connection — distinct from draining meetings",
    color: "#eeeeee",
  },
  {
    key: "content-comparison",
    effect: "drop" as const,
    label: "Instagram comparison spiral",
    sessions: 2,
    tiers: [2, 4],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T4 → T2",
    frequencyJump: "-1.0 tier",
    avgHr: "82 bpm spike",
    duration: "35 min avg",
    energy: "—",
    maxBeforeDrop: "—",
    note: "ENFP metrics trap — engagement scroll after posting",
    color: "#e6ba4a",
  },
  {
    key: "course-sprint-no-reflection",
    effect: "drop" as const,
    label: "Course sprint without reflection",
    sessions: 1,
    tiers: [2, 3],
    trackedDays: 1,
    days: "Mon",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.6 tier",
    avgHr: "70 bpm",
    duration: "4h 20m",
    energy: "—",
    maxBeforeDrop: "4h deep work",
    note: "Ideation scatter — skipped morning reflection",
    color: "#c4a46c",
  },
  {
    key: "design-overload",
    effect: "drop" as const,
    label: "Design management overload",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.5 tier",
    avgHr: "76 bpm",
    duration: "3h 40m avg",
    energy: "—",
    maxBeforeDrop: "3h stakeholder cap",
    note: "Too many revision rounds — no creative outlet same day",
    color: "#8ec0ff",
  },
  {
    key: "exercise-over-cap",
    effect: "drop" as const,
    label: "Exercise over capacity",
    sessions: 1,
    tiers: [2, 4],
    trackedDays: 1,
    days: "Thu",
    tierDelta: "T4 → T2",
    frequencyJump: "-0.8 tier next day",
    avgHr: "142 bpm peak",
    duration: "80 min total",
    energy: "512 kcal",
    maxBeforeDrop: "1h 20m / day",
    note: "Gym + run same day — Fri HRV bottomed 38 ms",
    color: "#6ecf9a",
  },
  {
    key: "draining-meetings",
    effect: "drop" as const,
    label: "Draining meetings",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.4 tier",
    avgHr: "72 bpm",
    duration: "4h blocks",
    energy: "Low NEAT",
    maxBeforeDrop: "3h social battery",
    note: "Administrative load — not the same as friends/family recharge",
    color: "#5a6a7a",
  },
  {
    key: "skipped-connection",
    effect: "drop" as const,
    label: "Skipped friends / family",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.5 tier",
    avgHr: "68 bpm",
    duration: "—",
    energy: "—",
    maxBeforeDrop: "—",
    note: "ENFP isolation trap — buried in course work, cancelled plans",
    color: "#eeeeee",
  },
  {
    key: "late-content-scroll",
    effect: "drop" as const,
    label: "Late content scroll",
    sessions: 2,
    tiers: [2, 3],
    trackedDays: 2,
    days: "Mon, Fri",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.3 tier",
    avgHr: "66 bpm",
    duration: "48 min avg",
    energy: "—",
    maxBeforeDrop: "30 min pre-bed",
    note: "Instagram + course notes after 22:30 — sleep score lag",
    color: "#4a7fd4",
  },
  {
    key: "sleep-debt",
    effect: "drop" as const,
    label: "Sleep under 6h 30m",
    sessions: 2,
    tiers: [2],
    trackedDays: 2,
    days: "Mon, Fri nights",
    tierDelta: "T3 → T2",
    frequencyJump: "-0.8 tier",
    avgHr: "52 bpm wake",
    duration: "6h 25m avg",
    energy: "218 kcal recovery",
    maxBeforeDrop: "6h 30m floor",
    note: "After late content nights — reflection skipped next AM",
    color: "#4a7fd4",
  },
] as const;

const BIOMETRIC_CORRELATIONS = [
  {
    indicator: "Reflection → creative output",
    biometric: "HRV + morning coherence",
    level: "Strong",
    r: "0.84",
    frequencyLink: "Reflection + Instagram content",
    outcome: "Tier 4 held 3 days when reflection logged first",
  },
  {
    indicator: "Course building flow",
    biometric: "Resting HR + HRV band",
    level: "Strong",
    r: "0.81",
    frequencyLink: "Course building under 4h",
    outcome: "Reality score peaked 8.4 Thu course block",
  },
  {
    indicator: "Restorative connection",
    biometric: "HRV rebound + social HR",
    level: "Strong",
    r: "0.77",
    frequencyLink: "Friends / family evenings",
    outcome: "+12 ms HRV vs draining meeting days",
  },
  {
    indicator: "Exercise recovery window",
    biometric: "Peak HR + next-day HRV",
    level: "Strong",
    r: "0.73",
    frequencyLink: "Exercise over 1h 20m",
    outcome: "HRV bottomed 38 ms Fri AM after Thu double session",
  },
  {
    indicator: "Content comparison spike",
    biometric: "HR spike + tier drop",
    level: "Strong",
    r: "0.69",
    frequencyLink: "Instagram comparison spiral",
    outcome: "T4 → T2 within 45 min on Fri",
  },
  {
    indicator: "Design without movement",
    biometric: "Sedentary load + tier",
    level: "Moderate",
    r: "0.58",
    frequencyLink: "Design management overload",
    outcome: "Tier slip when no exercise same day",
  },
] as const;

const WEEK_TOTAL_HOURS = 168;

const TIER_TIME = [
  { tier: 1, pct: 0, hours: "0h" },
  { tier: 2, pct: 28, hours: "47h 02m" },
  { tier: 3, pct: 43, hours: "72h 14m" },
  { tier: 4, pct: 29, hours: "48h 43m" },
  { tier: 5, pct: 0, hours: "0h" },
  { tier: 6, pct: 0, hours: "0h" },
] as const;

const PEAK_FREQUENCY = {
  peakTier: 4,
  name: "Energetic Mastery",
  longestBlock: "7h 00m",
  longestBlockWhen: "Thu Jun 6 · 07:00–14:00 · course building + design",
  daysAtPeak: 4,
  peakStreak: "Thu → Sat",
  peakStreakLabel: "3 days with T4 access",
  cumulativePeakHours: "48h 43m",
} as const;

const REALITY_LEVELS = [
  { level: "Low", score: "1–3", desc: "No visual or field change", active: false, manifestations: [] },
  { level: "Mid", score: "4–6", desc: "Subtle shift in perception", active: false, manifestations: [] },
  {
    level: "High",
    score: "7–8",
    desc: "Strong reality transformation",
    active: true,
    manifestations: [
      "Thu course outline: two collaborators adopted her framing in the design review without prompting",
      "Instagram batch felt effortless after reflection — colors logged as brighter for ~40 min (Thu 11:00)",
      "Partnership DM landed within 2h of Tier 4 course block — tagged 'exactly what we needed'",
    ],
  },
  { level: "Peak", score: "9–10", desc: "Steve Jobs–level distortion field", active: false, manifestations: [] },
] as const;

const FREQUENCY_TIERS = [
  { tier: 1, name: "Survival & Scarcity", active: false },
  { tier: 2, name: "Breaking the Illusion", active: false },
  { tier: 3, name: "ENCODED Activation", active: true },
  { tier: 4, name: "Energetic Mastery", active: true },
  { tier: 5, name: "Reality Architecture", active: false },
  { tier: 6, name: "Frequency Field Conductor", active: false },
] as const;

const TIER_PURE_STATS = [
  {
    tier: 2,
    name: "Breaking the Illusion",
    hoursInTier: "47h 02m",
    normalRestingHr: "62–68 bpm",
    normalHrRange: "62–74 bpm",
    normalHrvRange: "38–48 ms",
    normalRespiratoryRate: "14–16 /min",
    normalSleep: "6h 30m–7h",
    normalActiveEnergy: "280–380 kcal",
    normalRecovery: "58–68%",
    loggedRestingHr: "66 bpm",
    loggedHrVsNormal: "Within range · spikes to 78 bpm under load",
    loggedHrv: "44 ms avg",
    loggedHrvVsNormal: "Low end of band · sleep debt pulls down",
    loggedRespiratoryRate: "15.2 /min",
    loggedSleep: "6h 28m avg",
    loggedActiveEnergy: "318 kcal / day",
    loggedRecovery: "64%",
    loggedSteps: "7,180",
    stateNote: "Reactive loops · Instagram comparison spikes Mon + Fri",
  },
  {
    tier: 3,
    name: "ENCODED Activation",
    hoursInTier: "72h 14m",
    normalRestingHr: "58–64 bpm",
    normalHrRange: "58–68 bpm",
    normalHrvRange: "48–56 ms",
    normalRespiratoryRate: "12–14 /min",
    normalSleep: "7h–7h 30m",
    normalActiveEnergy: "360–440 kcal",
    normalRecovery: "70–78%",
    loggedRestingHr: "62 bpm",
    loggedHrVsNormal: "Center of band · stable across journal days",
    loggedHrv: "51 ms avg",
    loggedHrvVsNormal: "On target · +8% vs prior week",
    loggedRespiratoryRate: "14.0 /min",
    loggedSleep: "7h 05m avg",
    loggedActiveEnergy: "398 kcal / day",
    loggedRecovery: "74%",
    loggedSteps: "8,420",
    stateNote: "Coherent · reflection + design management hold tier",
  },
  {
    tier: 4,
    name: "Energetic Mastery",
    hoursInTier: "48h 43m",
    normalRestingHr: "52–58 bpm",
    normalHrRange: "52–62 bpm",
    normalHrvRange: "55–62 ms",
    normalRespiratoryRate: "11–13 /min",
    normalSleep: "7h 15m+",
    normalActiveEnergy: "400–520 kcal",
    normalRecovery: "78–86%",
    loggedRestingHr: "56 bpm",
    loggedHrVsNormal: "In range · drops to 52 bpm post-meditation",
    loggedHrv: "57 ms avg",
    loggedHrvVsNormal: "Upper band · peak Thu 58 ms",
    loggedRespiratoryRate: "12.8 /min",
    loggedSleep: "7h 22m avg",
    loggedActiveEnergy: "445 kcal / day",
    loggedRecovery: "82%",
    loggedSteps: "9,100",
    stateNote: "Field shift logged · course building peak Thu · reality 8.4",
  },
] as const;

export const courtneyConfareReport: FrequencyReportData = {
  memberName: "Courtney Confare",
  memberFirstName: "Courtney",
  memberArchetype: "ENFP",
  activityFocus:
    "Instagram content, design management, course building, exercise, reflection, friends & family",
  memberPhotoSrc: "/courtney confare.jpeg",
  reportCycle: REPORT_CYCLE,
  reportRange: REPORT_RANGE,
  introJournalEntries: "7 / 7 days",
  introDataPoints: "1,248",
  heroSubtitle: "",
  bandwidthSummary: "Accessible range Tier 3 → 4 · avg logged tier 3.1",
  hrvWeek: HRV_WEEK,
  sleepWeek: SLEEP_WEEK,
  watchDashboard: WATCH_DASHBOARD,
  weekFrequency: WEEK_FREQUENCY,
  activityCeilings: ACTIVITY_CEILINGS,
  activitiesInFrequency: ACTIVITIES_IN_FREQUENCY,
  biometricCorrelations: BIOMETRIC_CORRELATIONS,
  weekTotalHours: WEEK_TOTAL_HOURS,
  tierTime: TIER_TIME,
  peakFrequency: {
    ...PEAK_FREQUENCY,
    daysAtPeakList: "Tue, Wed, Thu, Sat",
    peakTimePct: "29% of week",
  },
  realityLevels: REALITY_LEVELS,
  frequencyTiers: FREQUENCY_TIERS,
  tierPureStats: TIER_PURE_STATS,
  realityDiaryScore: "7.8 / 10",
  realityPeakDay: "Thu",
  realityPeakScore: "8.4",
  wimHofTarget: "Target: 21 sessions · HRV baseline 51 ms → measure +10% goal",
  wimHofExperimentNote:
    "Courtney — log tier + HRV before each round and 10 min after. Target data: 63 breath sessions × 2 HRV reads = 126 new data points for correlation v0.5.",
  callBody:
    "Walk through this week's frequency pro report — Wim Hof protocol, 1,248 synced points, and Tier 3→4 bandwidth shift.",
};
